# Data Cleaning Notebook

The notebook contains the data cleaning process for the dynamic pricing ride-sharing dataset

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import os

Matplotlib is building the font cache; this may take a moment.

In [12]:
file_path = "../Data/Raw/dynamic_pricing(in).csv"

if os.path.exists(file_path):
    print("File found.")
else:
    print("File not found.")

File found.

In [14]:
df = pd.read_csv(file_path)
df.head()

,Number_of_Riders,Number_of_Drivers,Location_Category,Customer_Loyalty_Status,Number_of_Past_Rides,Average_Ratings,Time_of_Booking,Vehicle_Type,Expected_Ride_Duration,Historical_Cost_of_Ride
0,90,45,Urban,Silver,13,4.47,Night,Premium,90,284.257273
1,58,39,Suburban,Silver,72,4.06,Evening,Economy,43,173.874753
2,42,31,Rural,Silver,0,3.99,Afternoon,Premium,76,329.795469
3,89,28,Rural,Regular,67,4.31,Afternoon,Premium,134,470.201232
4,78,22,Rural,Regular,74,3.77,Afternoon,Economy,149,579.681422

In [16]:
df.shape

(1000, 10)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Number_of_Riders         1000 non-null   int64
 1   Number_of_Drivers        1000 non-null   int64
 2   Location_Category        1000 non-null   object
 3   Customer_Loyalty_Status  1000 non-null   object
 4   Number_of_Past_Rides     1000 non-null   int64
 5   Average_Ratings          1000 non-null   float64
 6   Time_of_Booking          1000 non-null   object
 7   Vehicle_Type             1000 non-null   object
 8   Expected_Ride_Duration   1000 non-null   int64
 9   Historical_Cost_of_Ride  1000 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 78.3+ KB

In [18]:
df.describe()

,Number_of_Riders,Number_of_Drivers,Number_of_Past_Rides,Average_Ratings,Expected_Ride_Duration,Historical_Cost_of_Ride
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,60.372000,27.076000,50.031000,4.257220,99.58800,372.502623
std,23.701506,19.068346,29.313774,0.435781,49.16545,187.158756
min,20.000000,5.000000,0.000000,3.500000,10.00000,25.993449
25%,40.000000,11.000000,25.000000,3.870000,59.75000,221.365202
50%,60.000000,22.000000,51.000000,4.270000,102.00000,362.019426
75%,81.000000,38.000000,75.000000,4.632500,143.00000,510.497504
max,100.000000,89.000000,100.000000,5.000000,180.00000,836.116419

## Column Names 
Checking if the columns have clear names and do not contain extra spaces

In [21]:
df.columns

Index(['Number_of_Riders', 'Number_of_Drivers', 'Location_Category',
       'Customer_Loyalty_Status', 'Number_of_Past_Rides', 'Average_Ratings',
       'Time_of_Booking', 'Vehicle_Type', 'Expected_Ride_Duration',
       'Historical_Cost_of_Ride'],
      dtype='object')

In [23]:
df_columns = df.columns.str.strip()
df_columns

Index(['Number_of_Riders', 'Number_of_Drivers', 'Location_Category',
       'Customer_Loyalty_Status', 'Number_of_Past_Rides', 'Average_Ratings',
       'Time_of_Booking', 'Vehicle_Type', 'Expected_Ride_Duration',
       'Historical_Cost_of_Ride'],
      dtype='object')

## Missing Values 
Checking if the dataset contains missing values

In [24]:
df.isnull().sum()

Number_of_Riders           0
Number_of_Drivers          0
Location_Category          0
Customer_Loyalty_Status    0
Number_of_Past_Rides       0
Average_Ratings            0
Time_of_Booking            0
Vehicle_Type               0
Expected_Ride_Duration     0
Historical_Cost_of_Ride    0
dtype: int64

No missing values were found in the dataset. No replacement or removal of missing data was necessary

## Duplicate Records
Checking if the dataset contains duplicate rows

In [25]:
df.duplicated().sum()

np.int64(0)

The duplicate check returned 0. This means that no dupliacte rows are in the dataset. Therefore, no rows have to be removed

## Categorical Variables

Checking the unique values in the categorical columns to identify possible spelling mistakes or inconsistent categories

In [26]:
df["Location_Category"].unique()

array(['Urban', 'Suburban', 'Rural'], dtype=object)

In [27]:
df["Customer_Loyalty_Status"].unique()

array(['Silver', 'Regular', 'Gold'], dtype=object)

In [28]:
df["Time_of_Booking"].unique()

array(['Night', 'Evening', 'Afternoon', 'Morning'], dtype=object)

In [29]:
df["Vehicle_Type"].unique()

array(['Premium', 'Economy'], dtype=object)

## Invalid Values

Checking if the numerical columns contain impossible values, such as negative numbers or ratings outside the expected range

In [30]:
df["Number_of_Riders"].min()

20

In [31]:
df["Number_of_Drivers"].min()

5

In [32]:
df["Average_Ratings"].min()

3.5

In [33]:
df["Average_Ratings"].max()

5.0

In [34]:
df["Expected_Ride_Duration"].min()

10

In [35]:
df["Historical_Cost_of_Ride"].min()

25.993449448411635

The numerical columns do not show impossible values. Rider count, driver count, ride duration, and ride cost are all positive.

For `Average_Ratings`, the values range from 3.5 to 5.0. Since this fits a typical 5-point rating scale, no rating values appear to be outside a reasonable range

## Save Cleaned Dataset

After checking column names, missing values, duplicate records, categorical values, and invalid numerical values, the dataset can be saved as a cleaned version

In [39]:
cleaned_file_path = "../Data/Cleaned/cleaned_dynamic_pricing.csv"
df.to_csv(cleaned_file_path, index=False)
print("Cleaned dataset saved")

Cleaned dataset saved

In [41]:
if os.path.exists(cleaned_file_path):
    print("File saved successfully.")
else:
    print("File was not saved.")

File saved successfully.